name: meimall
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.2.0+1
  dio: 2.0.0
  logger_flutter: ^0.7.1
  json_serializable: ^3.2.3
  city_pickers: ^0.1.30
  location: ^3.0.0
  oktoast: ^2.3.2
  flutter_verification_box: ^1.0.3
  camera: ^0.5.8+5
  barcode_scan: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.0
  json_serializable: ^3.2.3
  shared_preferences: ^0.5.8
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/zazhi.png
    - assets/images/zazhi_u.png
    - assets/images/shequ.png
    - assets/images/shequ_u.png
    - assets/images/shangdian.png
    - assets/images/wode.png
    - assets/images/wode_u.png
    - assets/images/fuwu_u.png
    - assets/images/fuwu.png
    - assets/images/shangdian_u.png
    - assets/images/logo_img.png
    - assets/images/home_magazine_top.png
    - assets/images/search.png
    - assets/images/scan.png
    - assets/images/video.png
    - assets/images/question.png
    - assets/images/broadcast.png
    - assets/images/look.png
    - assets/images/action.png
    - assets/images/camera.png
    - assets/images/unlogin.png
    - assets/images/me_pay.png
    - assets/images/me_payed.png
    - assets/images/me_scan.png
    - assets/images/me_info.png
    - assets/images/me_order.png
    - assets/images/me_pay_i.png
    - assets/images/me_setting.png
    - assets/images/me_shop.png
    - assets/images/me_store.png
    - assets/images/me_vip.png
    - assets/images/me_zone.png
    - assets/images/me_message.png
    - assets/images/qrcode.png
    - assets/images/login_code.png
    - assets/images/c_chat.png
    - assets/images/c_friend.png
    - assets/images/c_circle.png
    - assets/images/c_qchat.png
    - assets/images/good.png
    - assets/images/s_market.png
    - assets/images/s_note.png
    - assets/images/s_specialoffer.png
    - assets/images/f_call.png
    - assets/images/f_car.png
    - assets/images/f_charge.png
    - assets/images/f_deliver.png
    - assets/images/f_recycle.png
    - assets/images/s_takeout.png
    - assets/images/share.png
    - assets/images/popu_article.png
    - assets/images/popu_ask.png
    - assets/images/popu_fly.png
    - assets/images/popu_live.png
    - assets/images/popu_video.png
    - assets/images/earth.png
    - assets/images/pay_bg.png
    - assets/images/pay_recharge.png
    - assets/images/pay_cashout.png
    - assets/images/pay_trans.png
    - assets/images/pay_dill.png
    - assets/images/pay_property.png
    - assets/images/pay_welfare.png
    - assets/images/pay_renzheng.png
    - assets/images/pay_remainder.png
    - assets/images/pay_ali.png
    - assets/images/pay_wechat.png
    - assets/images/pay_slices.png
    - assets/images/pay_address_list.png
    - assets/images/pay_property_bg.png
    - assets/images/zone_bg.png
    - assets/images/zone_calendar.png
    - assets/images/zone_guest_bg.png
    - assets/images/zone_daily_bill.png
    - assets/images/z_carmera_s.png
    - assets/images/z_carmera_u.png
    - assets/images/z_loca_u.png
    - assets/images/z_loca_s.png
    - assets/images/z_pic_u.png
    - assets/images/z_pic_u.png
    - assets/images/z_video_u.png
    - assets/images/home_scan.png
    - assets/images/home_tra.png
    - assets/images/home_rec.png
    - assets/images/home_qr.png
    - assets/images/h_1.png
    - assets/images/h_4.png
    - assets/images/rec_parp.png
    - assets/images/rec_metal.png
    - assets/images/rec_plastic.png
    - assets/images/rec_fabrics.png
    - assets/images/rec_phone.png
    - assets/images/rec_scan.png
    - assets/images/rec_ondoor.png
    - assets/images/rec_h_1.png
    - assets/images/rec_h_2.png
    - assets/images/rec_h_3.png
    - assets/images/rec_h_4.png
    - assets/images/rec_h_5.png
    - assets/images/rec_h_6.png
    - assets/images/rec_h_7.png
    - assets/images/rec_h_8.png
    - assets/images/rec_h_loca.png
    - assets/images/recover_card.png
    - assets/images/ali_pay.png
    - assets/images/wechat_pay.png
    - assets/images/recoverman_points.png
    - assets/images/recoverman.png
    - assets/images/recoverman_storehouse.png
    - assets/images/r_profit_bg.png
    - assets/images/r_on_door.png
    - assets/images/r_pay.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: ali
      fonts:
        - asset: fonts/iconfont.ttf